[project]
name = "quick-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.21.1",
    "objectlistview3>=1.3.5",
    "python-dotenv>=1.1.1",
    "wxpython>=4.2.3",
]
