[project]
name = "quick-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "objectlistview3>=1.3.5",
    "wxpython>=4.2.3",
]
